[package]
name = "capy"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-node-v1.8.0" }

[addresses]
capy = "0x5d6605640f430521df2e7da9706ae111f0b3e8b9a6801b57ee4bca03e2ba7668"